name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - sebastienlevert/build23-demo
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - sebastienlevert/build23-demo

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_SMOKE_06C9D3210 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          output_location: 'samples/react-contoso/build' # Built app content directory - optional
          app_build_command: >
            npm run build:mgt-element &&
            npm run build:mgt-components &&
            npm run build:mgt-react &&
            npm run build:mgt-chat &&
            npx lerna run build --scope @microsoft/mgt-msal2-provider &&
            npm run build:react-contoso
          build_timeout_in_minutes: 30
          ###### End of Repository/Build Configurations ######
        env:
          REACT_APP_SITE_NAME: ${{secrets.REACT_APP_SITE_NAME}}
          REACT_APP_CLIENT_ID: ${{secrets.REACT_APP_CLIENT_ID}}
          REACT_APP_INCIDENTS_LIST_ID: ${{secrets.REACT_APP_INCIDENTS_LIST_ID}}
          REACT_APP_USER_INFORMATION_LIST_ID: ${{secrets.REACT_APP_USER_INFORMATION_LIST_ID}}
          REACT_APP_SUPPORT_GROUP_ID: ${{secrets.REACT_APP_SUPPORT_GROUP_ID}}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_SMOKE_06C9D3210 }}
          action: 'close'
